{% set name = "pynumero_libraries" %}
{% set version = "0.4" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/santiagoropb/pynumero_libraries/archive/v{{ version }}.tar.gz
  sha256: 5084868bd7d34e5ad393d85a09dfa62c010bf21e3beb892ee54ffce79c1c7e6d
    
build:
  number: 1000
  skip: true  # [win]
      
requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ampl-mp
    - python
    - numpy
  run:
    - python
    - ampl-mp
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  files:
    - test
    - simple_nlp.nl
    
about:
  home: https://github.com/santiagoropb/pynumero_libraries.git
  license: BSD
  license_file: LICENSE.txt
  summary: 'Libraries for PyNumero, a python package for numerical optimization'

extra:
  recipe-maintainers:
    - santiagoropb
