{% set name = "pynumero_libraries" %}
{% set version = "0.9" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/santiagoropb/pynumero_libraries/archive/v{{ version }}.tar.gz
  sha256: 37c4a3c8160f1f10315f4794d077cee5c855734ebbffa49dafca4173ec8d9f19
    
build:
  number: 0
  skip: true  # [win and vc<14]
  
requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ampl-mp  # [not win]
    - python  
    - numpy  
    - pymumps  # [not win]
    - matplotlib  # [not win]
    - scipy  # [not win]
  run:
    - python  
    - ampl-mp  # [not win] 
    - {{ pin_compatible('numpy') }} 
    - scipy  # [not win]
    - matplotlib  # [not win]
    - pymumps  # [not win]

test:
  files:
    - test  
    - simple_nlp.nl  
    
about:
  home: https://github.com/santiagoropb/pynumero_libraries.git
  license: BSD
  license_file: LICENSE.txt
  summary: 'Libraries for PyNumero, a python package for numerical optimization'

extra:
  recipe-maintainers:
    - santiagoropb
    - carldlaird
    - michaelbynum
