{% set name = "pynumero_libraries" %}
{% set version = "0.6" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/santiagoropb/pynumero_libraries/archive/v{{ version }}.tar.gz
  sha256: e452f38ed102c0432c1d5058766e25cd003763b704fa82027fec97232df3e20f
    
build:
  number: 0
      
requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ampl-mp  # [not win]
    - python  # [not win]
    - numpy  # [not win]
    - pymumps  # [not win]
    - matplotlib  # [not win]
    - scipy  # [not win]
  run:
    - python  # [not win]
    - ampl-mp  # [not win] 
    - {{ pin_compatible('numpy') }}  # [not win]
    - scipy  # [not win]
    - matplotlib  # [not win]
    - pymumps  # [not win]

test:
  files:
    - test
    - simple_nlp.nl
    
about:
  home: https://github.com/santiagoropb/pynumero_libraries.git
  license: BSD
  license_file: LICENSE.txt
  summary: 'Libraries for PyNumero, a python package for numerical optimization'

extra:
  recipe-maintainers:
    - santiagoropb
