{% set name = "pynumero_libraries" %}
{% set version = "0.5" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/santiagoropb/pynumero_libraries/archive/v{{ version }}.tar.gz
  sha256: cf21b5045aa18c636b4e2e13fe4f42119b0a4b0ccef96e43d4e5876f675d78a7
    
build:
  number: 0
      
requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ampl-mp  # [not win]
    - python
    - numpy
    - pymumps  # [not win]
    - matplotlib
    - scipy
  run:
    - python
    - ampl-mp  # [not win] 
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib
    - pymumps  # [not win]

test:
  files:
    - test
    - simple_nlp.nl
    
about:
  home: https://github.com/santiagoropb/pynumero_libraries.git
  license: BSD
  license_file: LICENSE.txt
  summary: 'Libraries for PyNumero, a python package for numerical optimization'

extra:
  recipe-maintainers:
    - santiagoropb
