appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: p7wByzUOSKSgYWEu5a63Lhn9GX/R9w5zs/ITTcG4zYk+LJrmsNY7fP68kAx1qTSXeVWfYAiWjtuwSR4toDq1ndGcLuAjuBI9AeOekS9aSsTF6OfriFO9RffNoqjr5lDwnm8g4ul8pxdmpymyx3Se13WhZ23cBX2zuMtHdFpJ0dvXiZS2bhWF8MD6b8XVW3YplwFPF75txTllycPHS1jllreUh+1Guc5glJe+GB92ub5mITd+4QyOhkrywYG9BUKYq4vqrSztPn0kPWRWqBX2qVbYHecZVgEeyAAFPeJ1g9JdizwHpPqnMo1SmXrFwnLXO/Zkty16dyHL2GRgSN78pHvs7BU87MTZGfpfrDwT6I55VM0OYrq42YvYjtYN6RRcVL12PLvLM4mL/6TDOz8A+taQP8CJS9NfK+NRF9lafSHlWBcsPGxhFuckrKR7Gv6/UKSHjgB4SJTv//aApKnAzYknL/hzGerCR/Rp/m1cPFQVbrxjMHhZvIwwCzLl32SWR46J3V/8F+jc0Il0ENSLIhTsOfOMCm2nuWafe6ssKjMJpo7+K4La0MMGPZDd8h3Q7nkSDFWIb3fGxDnkDqpNg5jX494fbU9X4xynKb2XbBkcEqBJr+wisAbfxeoANpuQAGVl43EGgqgHTt2pJWEvyh4zxV1rcplQgyWoWWKmaA8=}
